### ISSUE TITLE
Generate report

### ISSUE THREAD

**Issue by roydekleijn** [allure-examples/allure-gradle-testng-example#1]
Hello,

Can we automatically generate the report from a gradle build?

**Comment by baev** [comment]
Hi. You can use gradle exec and Allure CLI

**Comment by vania-pooh** [comment]
@roydekleijn we don't yet provide Gradle plugin for that becase there's no demand. So what @baev recommends is just a possible solution. If you're e.g. using Jenkins or Teamcity you can use respective plugin to generate Allure.
