### ISSUE TITLE
how to view allure report locally with gradle and testng

### ISSUE THREAD

**Issue by qianyiliushang** [allure-examples/allure-gradle-testng-example#4]
Is there a way to view test report locally with gradle and testng?

The report is displayed on the Jenkins server, but I cannot find a way to view them locally.

**Comment by vania-pooh** [comment]
Just open index.html from the report directory. :)

**Comment by qianyiliushang** [comment]
Command aborted due to exception {}.
ru.yandex.qatools.allure.command.AllureCommandException: Can't open report: directory <allure-report> doesn't exist.
        at ru.yandex.qatools.allure.command.ReportOpen.runUnsafe(ReportOpen.java:36)
        at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
        at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)

**Comment by vania-pooh** [comment]
Just open index.html in any browser except Chrome.

**Comment by just-boris** [comment]
By default, Allure looks for a report in `allure-results` directory.
If you have reported in another directory, pass it as parameter

```
allure report open --report-dir your-directory
```

**Comment by qianyiliushang** [comment]
![allure-report](https://cloud.githubusercontent.com/assets/6229122/14665155/5d7119f8-0703-11e6-929c-977ebc23f5d3.png)
@just-boris 
see the snapshot above,the report does not display as jenkins does

**Comment by vania-pooh** [comment]
@qianyiliushang I would say you're specifying wrong directory (with XML results). Need to specify directory where index.html resides.

**Comment by qianyiliushang** [comment]
@vania-pooh 
Thanks for your reply, seems the index.html is the test result of which gradle generated.
but I wanna to open report with allure.

see the settings in my build.gradle
```
group 'com.zombie'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

configurations {
    agent
}
repositories {
    maven {
        url "http://192.168.16.214:8081/repository/maven-public/"
    }
    mavenCentral()
}

dependencies {
    testCompile(
            'org.testng:testng:6.8.21',
            "ru.yandex.qatools.allure:allure-testng-adaptor:1.5.0-RC1"
    )
    compile(
            'com.jayway.restassured:rest-assured:2.9.0',
            'com.jayway.restassured:json-schema-validator:2.9.0',
            'com.jayway.restassured:scala-support:2.9.0',
            'org.apache.logging.log4j:log4j-api:2.2',
            'org.apache.logging.log4j:log4j-core:2.2',
            'org.slf4j:slf4j-jdk14:1.5.6',
            'com.alibaba:fastjson:1.2.8',
            'com.google.code.gson:gson:2.3.1',
            'org.codehaus.jackson:jackson-mapper-asl:1.9.11',
            'com.alibaba:fastjson:1.2.8',
            'org.apache.poi:poi:3.14',
            'org.apache.poi:poi-ooxml:3.14',
            'org.apache.poi:poi-ooxml-schemas:3.14',
            'org.apache.poi:poi-scratchpad:3.14',
    )
    agent "org.aspectj:aspectjweaver:1.8.8"

}

task wrapper(type: Wrapper) {
    gradleVersion = '2.10'
}

task copyJars(type:Copy){
    from configurations.runtime
    into 'libs'
}

test.doFirst {
    jvmArgs "-javaagent:${configurations.agent.singleFile}"
}

test {
    useTestNG() {
        suiteXmlFiles << new File(rootDir, "testng.xml")
    }
}
```

Below is gradle build test report

> ├── reports
│   └── tests
│       ├── classes
│       │   └── com.zombie.test.FastJsonUtilTest.html
│       ├── css
│       │   ├── base-style.css
│       │   └── style.css
│       ├── index.html
│       ├── js
│       │   └── report.js
│       └── packages
│           └── com.zombie.test.html


And the allure-results is in target folder which looks like this
> ├── target
│   └── allure-results
│       └── d83efa01-0494-4884-a7f6-635f073a54f8-testsuite.xml

**Comment by smecsia** [comment]
@qianyiliushang I would recommend you to override the default allure results directory to place allure results under the `build` directory. To do this you need to add `allure.properties` file with the following content to your classpath (e.g. resources directory): 
```
allure.results.directory=build/allure-results
```
Then, after the test execution has completed, you can build and open your report with Allure CLI:
```
$ allure generate -o build/reports/allure -- build/allure-results
$ allure report open -o build/reports/allure/
```

**Comment by qianyiliushang** [comment]
@smecsia 
It works，thanks for your kind help!
